### ISSUE TITLE
Crash on adding parallel

### ISSUE THREAD

**Issue by Defuera** [dtx12/AndroidAnimationsActions#3]
```
    play(forever(parallel(
                    sequence(
                            scaleBy(2f, 2f, 2, Interpolations.QuadraticEaseOut),
                            scaleBy(-2f, -2f),
                            delay(0.2f)
                    ),
                    fadeOut())
    ), radar);
```

stacktrace:
8-13318/com.justd.startupfabrictest E/AndroidRuntime: Process: com.justd.startupfabrictest, PID: 13318
java.lang.IllegalStateException: target is not specified!
at com.dtx12.android_animations_actions.actions.TypedAction.updateValues(TypedAction.java:68)
at com.dtx12.android_animations_actions.actions.TypedAction.start(TypedAction.java:59)
at android.animation.AnimatorSet.start(AnimatorSet.java:586)
at android.animation.AnimatorSet.start(AnimatorSet.java:586)
at com.dtx12.android_animations_actions.actions.RepeatAction.start(RepeatAction.java:53)
at com.dtx12.android_animations_actions.actions.Actions.play(Actions.java:506)
at com.justd.startupfabrictest.MainActivity.playRadarAnimation(MainActivity.java:69)
at com.justd.startupfabrictest.MainActivity.access$000(MainActivity.java:35)
at com.justd.startupfabrictest.MainActivity$1$1.run(MainActivity.java:130)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

MainActivity 69 is the first line, with play() function

**Comment by Defuera** [comment]
After some more tests I figured out, that parallel cannot contain sequence, neither sequence can contain parallel

**Comment by dtx12** [comment]
Fixed, thanks!
